# https://hub.docker.com/_/rabbitmq
FROM rabbitmq:3-management

# Creating a Dockerfile will have them enabled at runtime. To see the full list of plugins present on the image rabbitmq-plugins list
RUN rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_amqp1_0

